[project]
name = "building-effective-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "langchain-anthropic>=0.3.10",
    "langchain-core>=0.3.51",
    "langgraph>=0.3.28",
]
